version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: diff -u <(echo -n) <(gofmt -d .)
      - run: go test -race -vet "all" -v ./...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
